package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
)

func isInt(input string) bool {
	if _, err := strconv.Atoi(input); err == nil {
		return false
	}
	return true
}

func main() {
	//Needs input for code, num  uses, description, and expiration

	reader := bufio.NewReader(os.Stdin)
	fmt.Print("Enter New Code (leave empty if you want an autogenerated code): ")
	newCode, _ := reader.ReadString('\n')
	if newCode == "" {
		//Autogenerate code
	}

	fmt.Print("Enter Description: ")
	newDesc, _ := reader.ReadString('\n')

	fmt.Print("Enter Number of uses (leave empty if there are unlimited number of uses): ")
	numUses, _ := reader.ReadString('\n')
	//Check if numUses is an int
	for !isInt(numUses) {
		fmt.Print("You did not enter a number, please try again: ")
		numUses, _ = reader.ReadString('\n')
	}

	fmt.Print("Enter Expiration date in MM/DD/YY forma (leave empty if code does not expire): ")
	expiration, _ := reader.ReadString('\n')
	//Use magic regex to check format of expiration date

	fmt.Println(newCode, newDesc, numUses, expiration)

}
