package main

import (
	"bufio"
	"fmt"
	"log"
	"math/rand"
	"os"
	"strconv"

	post "github.com/sea350/ustart_go/post/guestCode"
	"github.com/sea350/ustart_go/types"
	elastic "gopkg.in/olivere/elastic.v5"
)

func isInt(input string) bool {
	if _, err := strconv.Atoi(input); err != nil {
		fmt.Println(input)
		return false
	}
	return true
}

const letterBytes = "ABCDEFGHJKLMNPQRSTUVWXYZ1234567890"

func randStringBytes(n int) string {
	b := make([]byte, n)
	for i := range b {
		b[i] = letterBytes[rand.Intn(len(letterBytes))]
	}
	return string(b)
}

func main() {
	var eclient, _ = elastic.NewSimpleClient(elastic.SetURL("http://localhost:9200"))

	reader := bufio.NewReader(os.Stdin)
	fmt.Print("Enter New Code (leave empty if you want an autogenerated code): ")
	newCode, _ := reader.ReadString('\n')
	newCode = newCode[:len(newCode)-1]
	if newCode == "" {
		//Autogenerate code
		newCode = randStringBytes(8)
	}

	//Take in description
	fmt.Print("Enter Description: ")
	newDesc, _ := reader.ReadString('\n')
	//remove newline from end
	newDesc = newDesc[:len(newDesc)-1]

	//Take in number of uses and checks if it's an integer
	var intNumUses int
	fmt.Print("Enter Number of uses (leave empty if there are unlimited number of uses): ")
	numUses, _ := reader.ReadString('\n')
	numUses = numUses[:len(numUses)-1]
	if numUses != "" {
		for !isInt(numUses) {
			fmt.Print("You did not enter a number, please try again: ")
			numUses, _ = reader.ReadString('\n')
			numUses = numUses[:len(numUses)-1]
			if numUses == "" {
				break
			}
		}
		intNumUses, err := strconv.Atoi(numUses)
		if intNumUses == 0 {
		}
		if err != nil {
			log.SetFlags(log.LstdFlags | log.Lshortfile)
			log.Println(err)
		}
	}

	//Take in expiration date
	fmt.Print("Enter Expiration date in MM/DD/YYYY format (leave empty if code does not expire): ")
	expiration, _ := reader.ReadString('\n')
	expiration = expiration[:len(expiration)-1]
	//Use magic regex to check format of expiration date

	var classification int

	switch {
	case numUses == "" && expiration == "":
		classification = 0
	case numUses != "" && expiration == "":
		classification = 1
	case numUses == "" && expiration != "":
		classification = 2
	case numUses != "" && expiration != "":
		classification = 3
	}

	fmt.Println("newCode: ", newCode)
	fmt.Println("newDesc: ", newDesc)
	fmt.Println("numUses: ", intNumUses)
	fmt.Println("expiration: ", expiration)
	fmt.Println("classification: ", classification)

	newGuestCode := types.GuestCode{Code: newCode, Description: newDesc, NumUses: intNumUses, Classification: classification}
	_, err := post.IndexGuestCode(eclient, newGuestCode)
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("Success!")
	}

}
